### ISSUE TITLE
Uglify package has vulnerability

### ISSUE THREAD

**Issue by anistark** [iotanetwork/website#1]
<img width="736" alt="screen shot 2018-04-09 at 2 20 48 am" src="https://user-images.githubusercontent.com/5357586/38472380-bfb932c4-3b9c-11e8-949e-b069afee3231.png">

Given the vulnerability, update the package and the packages used by this package accordingly.

**Comment by kevinley** [comment]
updated the uglify package to version 3.* and included it in dev dependencies but I have no access to push a new branch..

**Comment by anistark** [comment]
@kevinley access granted.
